application:
  config:
    domain-detect:
      enable: true
      timeout: 3000
      concurrency: 128
      provider:
        - 1.1.1.1
        - 8.8.8.8

    exclude:
      # 屏蔽此域会导致Edge浏览器翻译不可用
      - "edge.microsoft.com"
      # 屏蔽此域会导致小米天气网络异常
      - "metok.sys.miui.com"
      # 屏蔽此域会导致10086 App登陆异常
      - "client.app.coc.10086.cn"
      # 屏蔽此域会导致MSN页面无法正常加载
      - "assets.msn.com"

  # 规则源配置
  # remote为远程规则，local为本地规则，支持多个规则源
  rule:
    remote:
      - name: AdGuard Cookie通知过滤器
        path: https://filters.adtidy.org/android/filters/18_optimized.txt
        type: easylist

      - name: AdGuard 弹窗过滤器
        path: https://filters.adtidy.org/android/filters/19_optimized.txt
        type: easylist

      - name: AdGuard 移动拦截程序横幅广告的过滤器
        path: https://filters.adtidy.org/android/filters/20_optimized.txt
        type: easylist

      - name: AdGuard 其他恼人广告过滤器
        path: https://filters.adtidy.org/android/filters/21_optimized.txt
        type: easylist

      - name: AdGuard 恼人广告过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt
        type: easylist

      - name: Online Malicious URL Blocklist
        path: https://urlhaus-filter.pages.dev/urlhaus-filter-ag-online.txt
        type: easylist

      - name: AdGuard 小工具过滤器
        path: https://filters.adtidy.org/android/filters/22_optimized.txt
        type: easylist

#      - name: 解除广告和自我推销过滤器
#        path: https://filters.adtidy.org/android/filters/10_optimized.txt
#        type: easylist

#      - name: NoAppDownload
#        path: https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt
#        type: easylist

#      - name: xndeye web-ad-rule
#        path: https://raw.githubusercontent.com/xndeye/web-ad-rule/master/easylist.txt
#        type: easylist

#      - name: xinggsf movie
#        path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt

#      - name: damengzhu jiekouAD
#        path: https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt

#      - name: cjxlist annoyance
#        path: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt

#      - name: ABP filters
#        path: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt

      - name: ABP 反广告过滤
        path: https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt

#      - name: uBlockOrigin privacy
#        path: https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/privacy.txt

#      - name: Telemetry Lists - Aggregated
#        path: https://raw.githubusercontent.com/SystemJargon/filters/refs/heads/main/telemetry.txt

#      - name: GoodbyeAds-Xiaomi
#        path: https://cdn.jsdelivr.net/gh/jerryn70/GoodbyeAds@master/Extension/GoodbyeAds-Xiaomi-Extension.txt

#      - name: GoodbyeAds-Huawei
#        path: https://cdn.jsdelivr.net/gh/jerryn70/GoodbyeAds@master/Extension/GoodbyeAds-Huawei-AdBlock.txt

#      - name: GoodbyeAds-Samsung
#        path: https://cdn.jsdelivr.net/gh/jerryn70/GoodbyeAds@master/Extension/GoodbyeAds-Samsung-AdBlock.txt

      - name: xndeye adblock list of easylist
        path: https://raw.githubusercontent.com/xndeye/adblock_list/refs/heads/release/easylist.txt
   
      - name: TT拒绝列表
        path: https://ghproxy.net/https://raw.githubusercontent.com/TTDNS/Cat/refs/heads/main/TT%E6%8B%92%E7%BB%9D%E5%88%97%E8%A1%A8%E6%B8%85%E5%8D%95%20(%E6%9B%B4%E6%96%B0%E4%B8%AD).txt
  
      - name: AdGuard Tracking Protection filter (Optimized)
        path: https://filters.adtidy.org/android/filters/3_optimized.txt
        type: easylist
 
      - name: Bypass Paywalls Clean filter
        path: https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt

      - name: 晴雅广告拦截规则重置版支持IOS
        path: http://rssv.cn/adguard/api.php?type=black
      
      - name: HyperADRules
        path: https://raw.githubusercontent.com/Lynricsy/HyperADRules/master/rules.txt

      - name: all.txt
        path: https://raw.githubusercontent.com/afwfv/DD-AD/main/rule/all.txt

      - name: 去广告规则，酷安反馈反馈
        path: https://raw.githubusercontent.com/qq5460168/666/refs/heads/master/rules.txt

      - name: AdRules 橘猫
        path: https://adrules.5iclub.us.kg/adblock.txt
    
      - name: NEO DEV HOST
        path: https://raw.githubusercontent.com/neodevpro/neodevhost/master/adblocker

      - name: AdBlock Filter
        path: https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockfilters.txt

      - name: AdBlock DNS
        path: https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt 
        
      - name: 去广告规则，反馈🐧群请点击主页
        path: https://raw.githubusercontent.com/qq5460168/dangchu/main/black.txt

      - name: DD-AD
        path: https://raw.githubusercontent.com/afwfv/DD-AD/refs/heads/release/easylist.txt
 
      - name: HaGeZi's Pro DNS Blocklist
        path: https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/adblock/pro.txt

      - name: 1Hosts (Lite)
        path: https://raw.githubusercontent.com/badmojr/1Hosts/refs/heads/master/Lite/adblock.txt
        
      - name: JiuYue_Rules
        path: https://rules.vlo.cc/dns/dns.txt        
        
       
  output:
    file_header: |
      Title: wiz adblock list of ${type}
      Last Modified: ${date}
      Homepage: https://github.com/ALLOVERleng/ad-filters-subscriber
    
    files:
      - name: easylist.txt
        type: easylist
        filter:
          - basic
          - wildcard
          - unknown

      - name: dns.txt
        type: easylist
        file_header: |
          Title: wiz adblock list of dns 
          Last Modified: ${date}
        filter:
          - basic
          - wildcard

      - name: modify.txt
        type: easylist
        filter:
          - unknown

      - name: dnsmasq.conf
        type: dnsmasq

      - name: clash.yaml
        type: clash

      - name: smartdns.conf
        type: smartdns

      - name: hosts
        type: hosts
